### ISSUE TITLE
Exposing editable.js as AMD or CJS Modules

### ISSUE THREAD

**Issue by StatelessCat** [upfrontIO/editable.js#103]
Hey,
Does you plan to exposes ```editable.js```  as AMD or CJS Modules ?

When I'm tryin to use ```editable.js``` in RequireJS, I got ```Uncaught ReferenceError: bowser is not defined``` on [line 5781 of editable.js](https://github.com/upfrontIO/editable.js/blob/19d3aabf3a28666cc5558eb374de12422d579a43/editable.js#L5781).
Maybe I forgot something in my require.config ? : 
```js
require.config({
    ...
    paths: {
        ...
        "editable": "bower_components/editable/editable"
    },
    shim: {
        ...
        'editable': {
            deps: ['jquery'],
            exports: 'editable'
        }
    }
});
```

**Comment by peyerluk** [comment]
bowser is included in the editable.js file already. This is done in the `grunt concat` task ([Gruntfile.js#L77](https://github.com/upfrontIO/editable.js/blob/823f5fd27b4db1f12e7cd2c0d55995acf195d876/Gruntfile.js#L77)). Maybe concatening rangy, bowser and editable.js into one file is what's throwing AMD off. You can try building editable without adding bowser and rangy and load those separately (We do it like that in `examples/index.html` when testing).

And CommonJs is on its way: https://github.com/upfrontIO/editable.js/pull/102. We don't use AMD so could probably need some help with that.

**Comment by StatelessCat** [comment]
Thanks for the quick answer :) .

I'm not sure of what is wrong about bowser inside your bundled one file. But i have noted maybe something that can help.

I had the same issue when I was trying to uses editable.js without requireJS.
The bowser is not defined happend if i include editable.js after the requirejs (even if the requireJS is not using editable.js at all). Strange side effect.

To recap: 
## works ```:)``` : 
```
<script type="text/javascript" src="js/bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="js/bower_components/editable/editable.js"></script>
<script data-main="js/main" src="js/bower_components/requirejs/require.js"></script>
```
## don't works ```:(``` : 
```
<script data-main="js/main" src="js/bower_components/requirejs/require.js"></script>
<script type="text/javascript" src="js/bower_components/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="js/bower_components/editable/editable.js"></script>
```

I'm very glad to see you had started to exposes editable.js as CommonJS.
I think that is the best way actually to exposes JavaScript modules, until a few weeks(months?) ES6 modules become the standard (ES6 modules are already usable in production with [Babel](http://babeljs.io/)).
You probably don't want nor need to write AMD yourself, browserify with the ``` standalone``` option in a grunt task can produce an UMD module (exposing both AMD and CJS).

**Comment by viswesh** [comment]
Thank you for your efforts in developing and maintaining this library. 

I'm using version v0.6.2 (before ES2015 rewrite) with require js and bundling editable in a separate layer.
```
paths: { 
   "jquery": "vendor", 
   "backbone": "vendor", 
   "underscore": "vendor", 
   "Editable": "app"
 }
```
In the unminified version, require js is able to resolve Editable as the shim points to 'Editable' available at window.Editable. But in the minified app generated by r.js (require js optimizer), the app stops working due to Editable module timeout. In other words, require js is unable to resolve Editable.

Based on @peyerluk  suggestion, I ran 'grunt dev' to extract only the editable library (which is generated at .tmp/). This didn't work as well as - I get the following error -
```
Uncaught ReferenceError: $ is not defined 
   at app.js?t=20160320000000:3661 
   at Object.21../config (app.js?t=20160320000000:3928)
```
$ does not point to the window.$, hence it errors out. Including jquery at the top of editable.js works but that's just patchwork from my side.
```
Selection.prototype = $.extend(new Base(), {
```
Is there a way I can just use 'Editable' ES5 version? I can perhaps pull in rangy and bowser separately? 

As an alternative, I looked at /lib from version 1.0.0 (ES2015) but how do I consume it? I just need a single 'editable.js' only file which is ES5.
