### ISSUE TITLE
More than one editable div in a page

### ISSUE THREAD

**Issue by akar123** [upfrontIO/editable.js#152]
I have more than one editable div in a page/document. Ideally all events should be specific to its container. i.e. 

`var editable = new Editable()
editable.add($container);

editable.on('insert', function(){})
`

'insert' should only listen to 'insert' event being triggered on $container. 

As Dispatcher listens for the 'keydown.editable' event on entire document, if there are more than one editable div in one page, the 'insert' event will trigger for all of these divs.

I may be missing something obvious. Please let me know if there is any solution to overcome this problem.

**Comment by peyerluk** [comment]
This is by design. Editable only has one event emitter for all editable elements on a page. If you want to take action on events differently depending on the container an editable is in you can do so yourself. Every event also passes the element where the event was triggered.

So in your event listener you can check if the element is a child element of $container.
